### ISSUE TITLE
Starting Foobar2000 causes it to freeze if a music was playing or paused in a previous session

### ISSUE THREAD

**Issue by WagnerGFX** [stuerp/foo_vis_spectrum_analyzer#48] opened 2024-03-15 22:02 UTC
### Where?
- File > Preferences > Playback > [X] Save playback state when closing

### Details
- When the option above is enabled, Foobar will freeze when opening if there was any music playing or paused in the previous session.
- If it was playing, the music will still resume, even if everything else is frozen.
- There is no crash and Foobar must be terminated by Windows itself or Task Manager.
- Reopening normally will still cause the issue.
- The only fix is to run Foobar in safe mode (to stop the music) and then reopen it normally.
- The issue does not happen if the component is not present in the layout or is hidden.
- Re-enabling/showing the component before resuming the music also does not cause any issues.

### System Info:
- Windows 10 22H2
- Foobar2000 v1.6.16
- Visualizer v0.7.4.1

**Comment by stuerp** [comment] 2024-03-17 15:50
I did not know about that option.

However, I can't reproduce it with foobar2000 2.1.2. Even switching between the debug and release build of the component will not cause this behavior.

Is the whole fb2k UI frozen or just the component?

**Comment by WagnerGFX** [comment] 2024-03-17 18:35
> However, I can't reproduce it with foobar2000 2.1.2.

It could be a 1.6 issue. 😔

> Is the whole fb2k UI frozen or just the component?

It's the whole fb2k. To the point where Windows ask if I want to terminate the application.

![foobar freeze](https://github.com/stuerp/foo_vis_spectrum_analyzer/assets/16827309/f2cdfa56-0fcd-491f-823b-fb7da327d551)

**Comment by noisegrind3r** [comment] 2024-03-18 09:10
Same problem repeats only with columns UI layout and "Save playback state when closing" options

**Comment by stuerp** [comment] 2024-03-18 10:26
> Same problem repeats only with columns UI layout and "Save playback state when closing" options

Which version of foobar2000?

**Comment by noisegrind3r** [comment] 2024-03-18 12:12
Latest version, 2.1.2, portable. Clear installation without any component, except columns_ui and default options

**Comment by stuerp** [comment] 2024-03-18 17:22
Weird. I'll try to reproduce it but there is no clear reason. fb2k runs here on a continuous loop for at least 72h switching tracks every 3 seconds without a single hang-up or crash.

**Comment by stuerp** [comment] 2024-03-18 20:27
@WagnerGFX , @noisegrind3r ,

I think I fixed it.  I was looking in the wrong place. Please try:

https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha1

Please know that the spectogram feature is not finished yet.

**Comment by WagnerGFX** [comment] 2024-03-18 21:04
I can confirm that it's fixed for me 👍

**Comment by noisegrind3r** [comment] 2024-03-19 06:37
I also confirm that the problem has been solved. Thank you!

**Comment by stuerp** [comment] 2024-03-19 07:29
@WagnerGFX , @noisegrind3r ,

Thank you both for providing me enough information to fix this. I regret the day I switched to a separate render thread...

**Comment by stuerp** [comment] 2024-03-23 19:47
https://github.com/stuerp/foo_vis_spectrum_analyzer/releases/tag/v0.7.5.0-alpha2

**Closed by stuerp** 2024-03-23 19:47 UTC
Labels: bug
