### ISSUE TITLE
The correct way to average samples (or more accurately, downmix channels to mono) before FFT

### ISSUE THREAD

**Issue by TF3RDL** [stuerp/foo_vis_spectrum_analyzer#5] opened 2023-12-16 11:55 UTC
Right now, this spectrum visualization has unusually-high sidelobes (equivalent of rectangular window) when the audio data is stereo unless downmix channels to mono DSP is applied, due to its improper way to sum different channels of each sample into mono before FFT

**Comment by stuerp** [comment] 2023-12-20 15:04
I have turned that code inside out and can't find anything wrong with it. Unless you can pinpoint where my logic goes wrong I'm afraid this bug will remain unfixed.

**Comment by TF3RDL** [comment] 2024-01-02 20:30
I guess I've leave this open despite being "fixed", as I think a rigorous testing is required to see what this issue is truly fixed or not; if it is not, leave it open, and if it is fixed after very rigorous testing by @stuerp and HA members, close it (but not immediately)

**Comment by stuerp** [comment] 2024-01-27 19:16
I think I can close this now. There is no bug in the sample averaging; it was the caused by something else.

**Comment by TF3RDL** [comment] 2024-01-27 19:26
> I think I can close this now. There is no bug in the sample averaging; it was the caused by something else.

Fair enough, unless something pops up again (which I hopefully it doesn't happen again)

**Closed** 2024-01-27 21:31 UTC
Labels: bug
